# todo: for security reasons make local user

# base image
FROM node:12.20-alpine as build-stage

# set working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json'
COPY ./frontend/package*.json ./

# install project dependencies
RUN npm install

# copy source code
COPY ./frontend ./

RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage

RUN rm /etc/nginx/conf.d/default.conf

COPY ./deploy/production/nginx.frontend.conf /etc/nginx/conf.d/nginx.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html