# https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/python3.6-alpine3.8.dockerfile

# base image
FROM python:3.8-slim-buster

# format the standard output of python
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Change the working directory, every command after this will be run from the WORKDIR
RUN mkdir -p /code
WORKDIR /code

# copy requirements to WORKDIR
COPY ./requirements.txt ./

# install python dependencys
RUN pip install --upgrade pip
RUN pip install --no-cache-dir "uvicorn[standard]" gunicorn fastapi
RUN pip install --no-cache-dir -r requirements.txt

# copy source code to WORKDIR
COPY ./ ./